import Head from 'next/head'
import Image from 'next/image'
import {Button} from 'antd'
import styles from '../styles/Home.module.css'

const Home=()=> {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div>
        <Button>我是按钮</Button>
      </div>
    </div>
  )
}
export default Home
